// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

// Injectors from modules.go:

func ComposeApiServer(port HTTPPortNumber) (*apiServer, error) {
	processor := processorProvider()
	writer := writerProvider()
	httpHandlerFunc := httpHandler(processor, writer)
	mainApiServer := &apiServer{
		port:    port,
		handler: httpHandlerFunc,
	}
	return mainApiServer, nil
}
